# Running options
runs:
  train_run: True # train test run
  test_run: True # train model and store
  

# Declare paths
paths:
  # Directory of training groundthruth
  train_mask_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\training\groundtruth\1'
  # train_mask_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/groundtruth'
  # train_mask_dir: '/cluster/home/livios/data/training/training/groundtruth'
  
  # Directory of training images
  train_image_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\training\images\1'
  # train_image_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/images'
  # train_image_dir: '/cluster/home/livios/data/training/training/images'

  # Directory of test images
  test_image_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\test_images\test_images'
  # test_image_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/test_images/test_images'
  # test_image_dir: '/cluster/home/livios/data/test_images/test_images'

  # Directory for test output
  test_output_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\test_images'
  # test_output_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/test_images/test_output'
  #test_output_dir: '/cluster/home/livios/data/test_images/test_output'


# Model name
model_name: "bayesian_Unet"

# Number of classes for segmentation
num_classes: 2

# Set seed for reproducability
seed: 12345678

# Batch size for training (change depending on how much memory you have)
batch_size: 2

# Viusualize model output
visualize_model_output: True

# Number of epochs to train for
num_epochs: 1

# Proportion of the dataset used for validation split
val_size: 0.1

# Freeze pretrained layer weights
freeze: False

# Threshold probability when a pixel is classified as road
predict_threshold: 0.5

# Flag for feature extracting. When False, we finetune the whole model,
#   when True we only update the reshaped layer params
feature_extract: False

# Configure transforms
transforms:
  apply_transforms: False
  crop_size: 260

# Setting for Bayesian Unet
bm:
  in_channels: 3
  kl_weight: 0.00001
