
# Directory of training groundthruth
mask_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/groundtruth'
# Directory of training images
image_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/images'

# Number of classes for segmentation
num_classes: 2

# Set seed for reproducability
seed: 12345678

# Batch size for training (change depending on how much memory you have)
batch_size: 2

# Number of epochs to train for
num_epochs: 5

# Proportion of the dataset used for validation split
val_size: 0.1

# Freeze pretrained layer weights
freeze: False

# Flag for feature extracting. When False, we finetune the whole model,
#   when True we only update the reshaped layer params
feature_extract: False


# Configure transforms
transforms:
  apply_transforms: False
  crop_size: 260