# Running options
runs:
  train_run: True # train test run
  test_run: False # train model and store
 
# Model name
model_name: "bayesian_Unet"

# criterion
criterion:
  name: "BCE"
  weight_BCE: 0.5
  weight_Dice: 0.5
  BCE_reduction: "mean"
  pos_weight: None
  kl_weight: 0.00001

# Number of classes for segmentation
num_classes: 2

# Set seed for reproducability
seed: 12345678

# Batch size for training (change depending on how much memory you have)
batch_size: 3

# Viusualize model output
visualize_model_output: True
visualize_time: 5

# Number of epochs to train for
num_epochs: 20

# Proportion of the dataset used for validation split
val_size: 0.1

# Freeze pretrained layer weights
freeze: False

# Threshold probability when a pixel is classified as road
predict_threshold: 0.5

# Flag for feature extracting. When False, we finetune the whole model,
#   when True we only update the reshaped layer params
feature_extract: False

# Configure transforms
transforms:
  apply_transforms: True
  crop_size: 320

# Setting for Bayesian Unet
bm:
  in_channels: 3
