# Declare paths
paths:
  # Directory of training groundthruth
  # train_mask_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\training\groundtruth\1'
  train_mask_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/groundtruth_aug'
  train_mask_dir_aug: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/groundtruth_aug'
  # train_mask_dir: '/cluster/home/livios/data/training/training/groundtruth'
  
  # Directory of training images
  # train_image_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\training\images\1'
  train_image_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/images_aug'
  train_image_dir_aug: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/images_aug'
  # train_image_dir: '/cluster/home/livios/data/training/training/images'

  # Directory of test images
  # test_image_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\test_images\test_images'
  test_image_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/test_images/test_images'
  # test_image_dir: '/cluster/home/livios/data/test_images/test_images'

  # Directory for test output
  # test_output_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\test_images'
  test_output_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/test_images/test_output'
  #test_output_dir: '/cluster/home/livios/data/test_images/test_output'


# Model name
model_name: "deeplabv3"
checkpoint_name: "deeplab_epoch_800_jitter03_bce00_dice08_no_val_split"
# checkpoint_name: "checkpoint_test"

# Number of classes for segmentation
num_classes: 2

# Set seed for reproducability
seed: 12345678

# Batch size for training (change depending on how much memory you have)
batch_size: 2

# Viusualize model output
visualize_model_output: True
visualize_time: 30

# Number of epochs to train for
num_epochs: 50

# Proportion of the dataset used for validation split
use_train_val_split: False
val_size: 0.1

# Freeze pretrained layer weights
freeze: False

# Flag for feature extracting. When False, we finetune the whole model,
#   when True we only update the reshaped layer params
feature_extract: False

# Enable pseudo labeling
pseudo_labeling: False

# Configure transforms
transforms:
  apply_test_transforms: True
  apply_transforms: True
  crop_size: 224

# loss
loss:
  # Select desired loss
  # options: ["bce", "dice", "cl_dice"]
  name: "cl_dice" 
  patched_loss: True
  iter: 20
  alpha: 0.5
  smooth: 1
