# Declare paths
paths:
  # Directory of training groundthruth
  # train_mask_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\training\groundtruth\1'
  train_mask_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/groundtruth_aug'
  train_mask_dir_aug: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/groundtruth_aug'
  # train_mask_dir: '/cluster/home/livios/data/training/training/groundtruth'
  
  # Directory of training images
  # train_image_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\training\images\1'
  train_image_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/images_aug'
  train_image_dir_aug: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/training/training/images_aug'
  # train_image_dir: '/cluster/home/livios/data/training/training/images'

  # Directory of test images
  # test_image_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\test_images\test_images'
  test_image_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/test_images/test_images'
  # test_image_dir: '/cluster/home/livios/data/test_images/test_images'

  # Directory for test output
  # test_output_dir: 'C:\Users\svenk\OneDrive\Desktop\ETH_SS_21\Computational_Intelligence_Lab\Project\Data\test_images'
  test_output_dir: '/Users/livioschlapfer/Documents/OneDrive/Daten Livio/Schule/ETH/Master/2. Semester/Computational Intelligence Lab/3 - Project/2 - Data/cil-road-segmentation-2021/test_images/test_output'
  #test_output_dir: '/cluster/home/livios/data/test_images/test_output'


# Model name
model_name: "deeplabv3"
checkpoint_name: "pretrain_deeplab_dice"

# if run is to pretrain
pretrain: True

# Number of classes for segmentation
num_classes: 2

# Set seed for reproducability
seed_run: 2
seed: 90708 # [seed 1: 36573, seed 2: 90708, seed 3: 23012]

# Batch size for training (change depending on how much memory you have)
batch_size: 5

# Viusualize model output
visualize_model_output: False
visualize_time: 600

# Number of epochs to train for
num_epochs: 25

# Proportion of the dataset used for validation split
use_train_val_split: True
val_size: 0.1

# Continue training
continue_training: False
continue_training_on_checkpoint: "pretrain_deeplab_dice"

# Configure transforms
transforms:
  apply_test_transforms: True
  apply_transforms: True
  crop_size: 280
  flip_prob: 0.5
  rot_prob: 0.25
  canny: False
  canny_filter_size: 5
  canny_thresh: 250

#morphological postprocessing
morph:
  apply: False
  area_closing: True
  area_opening: True
  binary_closing: True
  iter: 1

# loss
loss:
  # Select desired loss
  # options: ["bce", "dice", "cl_dice", "focal"]
  name: "dice"
  patched_loss: True
  iter: 20
  alpha: 0.5
  smooth: 1
  bce_weight: 0.0

# lr
lr:
  init_lr: 0.0001
  lr_policy: "step" # options: ["none", linear", "step", "plateau"]

best_epoch: None